name: Deploy

on:
  push:
    branches:
      - main
      - 'releases/**'

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to AWS
      uses: reggionick/s3-deploy@v3
      with:
        folder: public
        bucket: ${{ secrets.S3_BUCKET }}
        dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        bucket-region: us-east-1
        private: true
        delete-removed: true
